var mongoose = require('mongoose');
var ListingsAndReviewsSchema = new mongoose.Schema({
  _id: Number,
  listing_url: String,
  name: String,
  summary: String,
  space: String,
  description: String,
  neighborhood_overview: String,
  notes: String,
  transit: String,
  access: String,
  interaction: String,
  house_rules: String,
  property_type: String,
  room_type: String,
  bed_type: String,
  minimum_nights: String,
  maximum_nights: String,
  cancellation_policy: String,
  last_scraped: { type: Date, default: Date.now },
  calendar_last_scraped: { type: Date, default: Date.now },
  first_review: { type: Date, default: Date.now },
  last_review: { type: Date, default: Date.now },
  accommodates: Number,
  bedrooms: Number,
  beds: Number,
  number_of_reviews: Number,
  bathrooms: Number,
  amenities: String,
  price: String,
  security_deposit: String,
  cleaning_fee: String,
  extra_people: String,
  guests_included: String,
  images: String,
  host: String,
  address: String,
  availability: String,
  review_scores: String,
  reviews: Array,
}, { timestamps: true });

module.exports = mongoose.model('ListingsAndReviews', ListingsAndReviewsSchema);